name: CMake

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Debug Environment
      run: |
        echo "=== Environment Debug ==="
        echo "Working directory: $(pwd)"
        echo "Ubuntu version: $(lsb_release -a)"
        echo "Available space: $(df -h .)"
        echo "CMAKE version: $(cmake --version)"
        echo "GCC version: $(gcc --version)"
        
    - name: Install SFML 3.0 Dependencies
      run: |
        echo "=== Installing SFML Dependencies ==="
        sudo apt update
        sudo apt install -y \
          build-essential \
          cmake \
          git \
          libfreetype6-dev \
          libopenal-dev \
          libvorbis-dev \
          libflac-dev \
          libudev-dev \
          libgl1-mesa-dev \
          libxrandr-dev \
          libxcursor-dev \
          libxi-dev \
          libx11-dev \
          pkg-config
        echo "Dependencies installed successfully"

    - name: Cache SFML Build
      uses: actions/cache@v3
      id: cache-sfml
      with:
        path: |
          /usr/local/lib/libsfml*
          /usr/local/include/SFML
          /usr/local/lib/cmake/SFML
        key: sfml-3.0.0-ubuntu-${{ runner.os }}-${{ hashFiles('**/CMakeLists.txt') }}

    - name: Build and Install SFML 3.0 from Source
      if: steps.cache-sfml.outputs.cache-hit != 'true'
      run: |
        echo "=== Building SFML 3.0 from Source ==="
        git clone --depth 1 --branch 3.0.0 https://github.com/SFML/SFML.git sfml-source
        cd sfml-source
        echo "SFML source downloaded, configuring build..."
        cmake -B build \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_INSTALL_PREFIX=/usr/local \
          -DSFML_BUILD_EXAMPLES=OFF \
          -DSFML_BUILD_DOC=OFF
        echo "Building SFML (this may take a few minutes)..."
        cmake --build build -j$(nproc) --config Release
        echo "Installing SFML..."
        sudo cmake --install build
        cd ..
        rm -rf sfml-source
        echo "SFML 3.0 installation completed"

    - name: Verify SFML Installation
      run: |
        echo "=== Verifying SFML Installation ==="
        echo "Checking SFML libraries:"
        ls -la /usr/local/lib/libsfml* || echo "No SFML libraries found"
        echo "Checking SFML headers:"
        ls -la /usr/local/include/SFML/ || echo "No SFML headers found"
        echo "Checking SFML CMake config:"
        ls -la /usr/local/lib/cmake/SFML/ || echo "No SFML CMake config found"
        echo "PKG_CONFIG_PATH: $PKG_CONFIG_PATH"
        echo "LD_LIBRARY_PATH: $LD_LIBRARY_PATH"

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: |
        echo "=== Configuring CMake ==="
        echo "CMAKE_PREFIX_PATH: $CMAKE_PREFIX_PATH"
        export CMAKE_PREFIX_PATH="/usr/local:$CMAKE_PREFIX_PATH"
        echo "Updated CMAKE_PREFIX_PATH: $CMAKE_PREFIX_PATH"
        cmake -B ${{github.workspace}}/build \
          -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
          -DCMAKE_PREFIX_PATH=/usr/local \
          -DSFML_DIR=/usr/local/lib/cmake/SFML \
          -DCMAKE_VERBOSE_MAKEFILE=ON

    - name: Build
      # Build your program with the given configuration
      run: |
        echo "=== Building DeerPortal ==="
        cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --verbose

    - name: Test
      working-directory: ${{github.workspace}}/build
      # Execute tests defined by the CMake configuration.  
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest -C ${{env.BUILD_TYPE}} --verbose
      
